### ISSUE TITLE
Java-Port

### ISSUE THREAD

**Issue by spotlesscoder** [0uti/UglyLauncher#1]
Hi,

is there a reason why you chose C# over Java? 

I'm currently thinking of making a Java version of the ugly launcher because my main systems run linux.

**Comment by 0uti** [comment]
this has a simple reason ... i don't like java :)
And all of the users have Windows and don't want to care about Java libraries.

**Comment by spotlesscoder** [comment]
Maybe I missed something but there shouldn't be a need for the users to care about Java libraries just because the an ugly launcher version made with Java.
